INSERT
OR REPLACE INTO LocalizedText (Tag, LANGUAGE, Text)
VALUES
    ('LOC_UNIT_TSOD_SCOUT_AMBER_NAME', 'zh_Hans_CN', '琥珀'),
    ('LOC_UNIT_TSOD_SCOUT_AMBER_DESCRIPTION', 'zh_Hans_CN', '塞西尔的特殊侦察单位，拥有独特的升级树。建立首都时自动获得，无法生产。初始拥有4视野，但正面战斗力极其薄弱。被击杀时将保留1点体力值，撤退至最近的城市。发现自然奇观与部落村庄时，获得三倍经验值。'),
    ('LOC_GREAT_PERSON_CLASS_TSOD_CE_SCIENTIST_NAME', 'zh_Hans_CN', '塞西尔的大科学家'),
    ('LOC_GREAT_PERSON_INDIVIDUAL_TSOD_CE_REBECCA_CECIL_NAME', 'zh_Hans_CN', '瑞贝卡·塞西尔'),
    ('LOC_GREATPERSON_DUMMY_TSOD_CE_REBECCA_CECIL_DUMMY_DESCRIPTION', 'zh_Hans_CN', '立即完成当前正在研究的科技。'),
    ('LOC_GREAT_PERSON_INDIVIDUAL_TSOD_CE_JENNIE_PERRO_NAME', 'zh_Hans_CN', '詹妮·佩罗'),
    ('LOC_GREATPERSON_GRANT_TECHNOLOGY_MATHEMATICS_DESCRIPTION', 'zh_Hans_CN', '立即完成数学科技。'),
    ('LOC_GREATPERSON_GRANT_BUILDING_TSOD_MANA_OBELISK_DESCRIPTION', 'zh_Hans_CN', '在市中心建造一个魔能方尖碑。'),
    ('LOC_GREAT_PERSON_INDIVIDUAL_TSOD_CE_SANTIS_SAIDE_NAME', 'zh_Hans_CN', '桑提斯·赛德'),
    ('LOC_GREATPERSON_SINGLE_CITY_ADD_4_SCIENCE_DESCRIPTION', 'zh_Hans_CN', '该城市+4[ICON_Science]科技。'),
    ('LOC_UNIVERSITY_BONUS_AMENITY_ATTACH_DESCRIPTION', 'zh_Hans_CN', '所有拥有大学的城市+1[ICON_Amenities]宜居度。'),
    ('LOC_GREATPERSON_TSOD_CE_SANTIS_SAIDE_ACTIVE', 'zh_Hans_CN', '立即在该区域建造大学和图书馆。该城市+4[ICON_Science]科技。所有拥有大学的城市+1[ICON_Amenities]宜居度。'),
    ('LOC_GREAT_PERSON_INDIVIDUAL_TSOD_CE_KAMEL_SLAYEN_NAME', 'zh_Hans_CN', '卡迈尔·斯雷恩'),
    ('LOC_GREATPERSON_ELECTRICITYTECHBOOST_DESCRIPTION', 'zh_Hans_CN', '为电力科技启动[ICON_TechBoosted]尤里卡时刻。'),
    ('LOC_GREATPERSON_DUMMY_TSOD_CE_KAMEL_SLAYEN_INSPIRATION_DESCRIPTION', 'zh_Hans_CN', '为文化遗产市政启动[ICON_CivicBoosted]鼓舞时刻。'),
    ('LOC_GREAT_PERSON_INDIVIDUAL_TSOD_CE_NORRIS_NAME', 'zh_Hans_CN', '诺里斯'),
    ('LOC_GREATPERSON_SINGLE_CITY_20_GROWTH_DESCRIPTION', 'zh_Hans_CN', '该城市人口增长速度增加20%。'),
    ('LOC_GREATPERSON_CITY_RICEWHEATYIELD_DESCRIPTION', 'zh_Hans_CN', '大米和小麦地块+1[ICON_Food]食物。'),
    ('LOC_GREAT_PERSON_CLASS_TSOD_CE_GOVERNOR_NAME', 'zh_Hans_CN', '塞西尔的大执政官'),
    ('LOC_GREAT_PERSON_INDIVIDUAL_TSOD_CE_HETTIE_CECIL_NAME', 'zh_Hans_CN', '赫蒂·塞西尔'),
    ('LOC_GREATPERSON_DUMMY_TSOD_CE_HETTIE_CECIL_REFUND_COAL_DESCRIPTION', 'zh_Hans_CN', '军事工程师建造铁路后会返还1点[ICON_RESOURCE_COAL]煤。'),
    ('LOC_GREATPERSON_AOE_TSOD_CE_HETTIE_CECIL_ATTACH_DESCRIPTION', 'zh_Hans_CN', '如果单位位于或相邻市中心，所在城市购买单位时-20%花费。'),
    ('LOC_GREAT_PERSON_CLASS_TSOD_CE_GENERAL_NAME', 'zh_Hans_CN', '塞西尔的大将军'),
    ('LOC_GREAT_PERSON_INDIVIDUAL_TSOD_CE_SIR_PHILIP_NAME', 'zh_Hans_CN', '菲利普'),
    ('LOC_GREATPERSON_SIEGE_UNIT_ATTACK_RANGE_ATTACH_DESCRIPTION', 'zh_Hans_CN', '攻城单位+1[ICON_Range]射程。'),
    ('LOC_GREATPERSON_SIEGE_UNIT_ATTACK_DAMAGE_BUFF_ATTACH_DESCRIPTION', 'zh_Hans_CN', '攻城单位对抗单位时没有减益并且+3[ICON_Bombard]轰炸攻击力。'),
    ('LOC_SIEGE_UNIT_ATTACK_DAMAGE_BUFF_VS_UNITS_NAME', 'zh_Hans_CN', '艺术'),
    ('LOC_SIEGE_UNIT_ATTACK_DAMAGE_BUFF_VS_UNITS_DESCRIPTION', 'zh_Hans_CN', '对抗单位时+20[ICON_Bombard]轰炸攻击力。'),
    ('LOC_GREATPERSON_COMBAT_STRENGTH_AOE_ALL_ERA_LAND_DESCRIPTION', 'zh_Hans_CN', '在两个单元格以内，为陆地单位+5[ICON_Strength]战斗力。'),
    ('LOC_GREAT_PERSON_CLASS_TSOD_CE_ADMIRAL_NAME', 'zh_Hans_CN', '塞西尔的海军统帅'),
    ('LOC_GREAT_PERSON_INDIVIDUAL_TSOD_CE_BYRON_KIRK_NAME', 'zh_Hans_CN', '拜伦·柯克'),
    ('LOC_GREATPERSON_COMBAT_STRENGTH_AOE_ALL_ERA_SEA_DESCRIPTION', 'zh_Hans_CN', '在两个单元格以内，为海军单位+5[ICON_Strength]战斗力。'),
    ('LOC_GREATPERSON_GRANT_INFLUENCE_TOKEN_DESCRIPTION', 'zh_Hans_CN', '获得1位[ICON_Envoy]使者。'),
    ('LOC_GREAT_PERSON_CLASS_TSOD_CE_PROPHET_NAME', 'zh_Hans_CN', '塞西尔的大牧首'),
    ('LOC_GREAT_PERSON_INDIVIDUAL_TSOD_CE_LEITE_AVIKEN_NAME', 'zh_Hans_CN', '莱特·艾维肯'),
    ('LOC_ABILITY_COMBAT_STRENGTH_AOE_RELIGIOUS_NAME', 'zh_Hans_CN', '大牧首的指引'),
    ('LOC_ABILITY_COMBAT_STRENGTH_AOE_RELIGIOUS_DESCRIPTION', 'zh_Hans_CN', '位于大牧首2单元格内时+5[ICON_Religion]宗教战斗力。'),
    ('LOC_COMBAT_STRENGTH_AOE_RELIGIOUS_DESCRIPTION', 'zh_Hans_CN', '在两个单元格以内，为宗教单位+5[ICON_Religion]战斗力。'),
    ('LOC_GREATPERSON_CITY_POPULATION_RELIGIOUS_YIELD_ATTACH_DESCRIPTION', 'zh_Hans_CN', '如果该城信仰任意宗教，城市中每位公民额外产出+0.5[ICON_Faith]信仰值。'),
    ('LOC_GREAT_PERSON_CLASS_TSOD_CE_MERCHANT_NAME', 'zh_Hans_CN', '塞西尔的大商人'),
    ('LOC_GREAT_PERSON_INDIVIDUAL_TSOD_CE_PITMAN_LAUREN_NAME', 'zh_Hans_CN', '皮特曼·劳伦'),
    ('LOC_GREATPERSON_GRANT_LUXURY_POTION_DESCRIPTION', 'zh_Hans_CN', '赠予2份[ICON_RESOURCE_TSOD_CE_POTION]炼金药剂，这是一种特殊的人造奢侈品资源，能+4[ICON_Amenities]宜居度。'),
    ('LOC_GREAT_PERSON_CLASS_TSOD_CE_WRITER_NAME', 'zh_Hans_CN', '塞西尔的大剧作家'),
    ('LOC_GREAT_PERSON_INDIVIDUAL_TSOD_CE_FELM_NAME', 'zh_Hans_CN', '菲尔姆'),
    ('LOC_GREAT_PERSON_CLASS_TSOD_CE_ENGINEER_NAME', 'zh_Hans_CN', '塞西尔的大工程师'),
    ('LOC_GREAT_PERSON_INDIVIDUAL_TSOD_CE_NICHOLAS_EGG_NAME', 'zh_Hans_CN', '尼古拉斯·蛋'),
    ('LOC_GREATPERSON_AOE_TSOD_CE_NICHOLAS_EGG_ATTACH_DESCRIPTION', 'zh_Hans_CN', '如果单位位于或相邻市中心，所在城市生产单位时+25%[ICON_Production]生产力。'),
    ('LOC_UNIT_TSOD_GORGON_PLATFORM_NAME', 'zh_Hans_CN', '戈尔贡平台'),
    ('LOC_UNIT_TSOD_GORGON_PLATFORM_DESCRIPTION', 'zh_Hans_CN', '塞西尔的独特支援单位，替代无人机。为1单元格内的攻城单位+1[ICON_Range]射程，+5[ICON_Strength]攻击力。能治疗邻近单位。'),
    ('LOC_TSOD_GORGON_PLATFORM_SIEGE_BONUS_DESCRIPTION', 'zh_Hans_CN', '相邻戈尔贡平台的攻城单位+5[ICON_Strength]攻击力。'),
    ('LOC_TSOD_GORGON_PLATFORM_SIEGE_BONUS_MODIFIER', 'zh_Hans_CN', '相邻戈尔贡平台+{1_Amount}战斗力。'),
    ('LOC_PROMOTION_CLASS_TSOD_SCOUT_AMBER_NAME', 'zh_Hans_CN', '琥珀'),
    ('LOC_PROMOTION_TSOD_CE_SHADOW_REALM_NAME', 'zh_Hans_CN', '暗影视界'),
    ('LOC_PROMOTION_TSOD_CE_SHADOW_REALM_DESCRIPTION', 'zh_Hans_CN', '+1视野范围，视野能穿过所有地形和地貌。'),
    ('LOC_PROMOTION_TSOD_CE_MASTER_THIEF_NAME', 'zh_Hans_CN', '南境盗圣'),
    ('LOC_PROMOTION_TSOD_CE_MASTER_THIEF_DESCRIPTION', 'zh_Hans_CN', '与受损单位战斗时+15[ICON_Strength]战斗力。'),
    ('LOC_PROMOTION_TSOD_CE_SHADOW_CREATURE_NAME', 'zh_Hans_CN', '暗影生物'),
    ('LOC_PROMOTION_TSOD_CE_SHADOW_CREATURE_DESCRIPTION', 'zh_Hans_CN', '+1[ICON_Movement]移动力。忽视所有地形带来的移动力减益'),
    ('LOC_PROMOTION_TSOD_CE_TAVERN_QUEEN_NAME', 'zh_Hans_CN', '酒馆女王'),
    ('LOC_PROMOTION_TSOD_CE_TAVERN_QUEEN_DESCRIPTION', 'zh_Hans_CN', '在友军领土之外恢复。在每回合结束时（甚至是在移动或攻击后），自动恢复生命值。'),
    ('LOC_PROMOTION_TSOD_CE_SHADOW_CHOSEN_NAME', 'zh_Hans_CN', '暗夜神选'),
    ('LOC_PROMOTION_TSOD_CE_SHADOW_CHOSEN_DESCRIPTION', 'zh_Hans_CN', '+1[ICON_Movement]移动力。只有相邻敌军单位才能发现该单位。'),
    ('LOC_PROMOTION_TSOD_CE_NIGHT_MISTRESS_NAME', 'zh_Hans_CN', '夜幕之城的女主人'),
    ('LOC_PROMOTION_TSOD_CE_NIGHT_MISTRESS_DESCRIPTION', 'zh_Hans_CN', '+1视野范围，显示视野范围内的隐形单位。'),
    ('LOC_PROMOTION_TSOD_CE_SHADOW_AUTHORITY_NAME', 'zh_Hans_CN', '暗影权能'),
    ('LOC_PROMOTION_TSOD_CE_SHADOW_AUTHORITY_DESCRIPTION', 'zh_Hans_CN', '攻击后可移动。+1对所有文明的外交等级。'),
    ('LOC_VIZSOURCE_TSOD_SCOUT_AMBER', 'zh_Hans_CN', '琥·总而言之就是超厉害·珀'),
    ('LOC_VIZSOURCE_ACTION_TSOD_SCOUT_AMBER', 'zh_Hans_CN', '将琥珀提升至最高等级。'),
    ('LOC_GOSSIP_SOURCE_TSOD_SCOUT_AMBER', 'zh_Hans_CN', '{1_Name}，发现了');

INSERT
OR REPLACE INTO BaseGameText (Tag, Text)
VALUES
    ('LOC_UNIT_TSOD_SCOUT_AMBER_NAME', 'Amber'),
    (
        'LOC_UNIT_TSOD_SCOUT_AMBER_DESCRIPTION',
        'Cecil''s unique recon unit with a unique Promotion tree. Automatically received upon establishing the Capital and cannot be produced. She starts with a vision range of 4 but has extremely weak combat strength. When killed, retreats with 1 HP to the nearest city. She gains three times the experience from revealing Natural Wonders and from visiting Tribal Villages.'
    ),
    ('LOC_GREAT_PERSON_CLASS_TSOD_CE_SCIENTIST_NAME', 'Great Scientist of Cecil'),
    ('LOC_GREAT_PERSON_INDIVIDUAL_TSOD_CE_REBECCA_CECIL_NAME', 'Rebecca Cecil'),
    ('LOC_GREATPERSON_DUMMY_TSOD_CE_REBECCA_CECIL_DUMMY_DESCRIPTION', 'Instantly complete the currently researching technology.'),
    ('LOC_GREAT_PERSON_INDIVIDUAL_TSOD_CE_JENNIE_PERRO_NAME', 'Jennie Perro'),
    ('LOC_GREATPERSON_GRANT_TECHNOLOGY_MATHEMATICS_DESCRIPTION', 'Instantly complete the Mathematics technology.'),
    ('LOC_GREATPERSON_GRANT_BUILDING_TSOD_MANA_OBELISK_DESCRIPTION', 'Construct a Mana Obelisk in the City Center.'),
    ('LOC_GREAT_PERSON_INDIVIDUAL_TSOD_CE_SANTIS_SAIDE_NAME', 'Santis Saide'),
    ('LOC_GREATPERSON_SINGLE_CITY_ADD_4_SCIENCE_DESCRIPTION', 'The city gains +4 [ICON_Science] Science.'),
    ('LOC_UNIVERSITY_BONUS_AMENITY_ATTACH_DESCRIPTION', 'All cities with a university receive +1 [ICON_Amenities] Amenity.'),
    ('LOC_GREAT_PERSON_INDIVIDUAL_TSOD_CE_KAMEL_SLAYEN_NAME', 'Kamel Slayen'),
    ('LOC_GREATPERSON_ELECTRICITYTECHBOOST_DESCRIPTION', 'Trigger a [ICON_TechBoosted] Eureka moment for the Electricity technology.'),
    (
        'LOC_GREATPERSON_DUMMY_TSOD_CE_KAMEL_SLAYEN_INSPIRATION_DESCRIPTION',
        'Trigger an [ICON_CivicBoosted] Inspiration moment for the Cultural Heritage civic.'
    ),
    ('LOC_GREAT_PERSON_INDIVIDUAL_TSOD_CE_NORRIS_NAME', 'Norris'),
    ('LOC_GREATPERSON_SINGLE_CITY_20_GROWTH_DESCRIPTION', 'The city gains 20% growth, stackable.'),
    ('LOC_GREATPERSON_CITY_RICEWHEATYIELD_DESCRIPTION', 'Rice and wheat plots gain +1 [ICON_Food] food each.'),
    ('LOC_GREAT_PERSON_CLASS_TSOD_CE_GOVERNOR_NAME', 'Great Governor of Cecil'),
    ('LOC_GREAT_PERSON_INDIVIDUAL_TSOD_CE_HETTIE_CECIL_NAME', 'Hettie Cecil'),
    ('LOC_GREATPERSON_DUMMY_TSOD_CE_HETTIE_CECIL_REFUND_COAL_DESCRIPTION', 'Refund 1 [ICON_RESOURCE_COAL] coal after building a railroad.'),
    (
        'LOC_GREATPERSON_AOE_TSOD_CE_HETTIE_CECIL_ATTACH_DESCRIPTION',
        'When the unit is at or adjacent to city center, reduce 20% cost when purchasing units in this city.'
    ),
    ('LOC_GREAT_PERSON_CLASS_TSOD_CE_GENERAL_NAME', 'Great General of Cecil'),
    ('LOC_GREAT_PERSON_INDIVIDUAL_TSOD_CE_SIR_PHILIP_NAME', 'Sir Philip'),
    ('LOC_GREATPERSON_SIEGE_UNIT_ATTACK_RANGE_ATTACH_DESCRIPTION', '+1 [ICON_Range] range to siege units.'),
    (
        'LOC_GREATPERSON_SIEGE_UNIT_ATTACK_DAMAGE_BUFF_ATTACH_DESCRIPTION',
        '+3 [ICON_Bombard] Bombard Strength to siege units vs. units, instead of the debuff.'
    ),
    ('LOC_SIEGE_UNIT_ATTACK_DAMAGE_BUFF_VS_UNITS_NAME', 'The "Art"'),
    ('LOC_SIEGE_UNIT_ATTACK_DAMAGE_BUFF_VS_UNITS_DESCRIPTION', '+20[ICON_Bombard] Bombard Stregth vs. units.'),
    ('LOC_GREATPERSON_COMBAT_STRENGTH_AOE_ALL_ERA_LAND_DESCRIPTION', '+5 [ICON_Strength] Combat Strength to land units within 2 tiles.'),
    ('LOC_GREAT_PERSON_CLASS_TSOD_CE_ADMIRAL_NAME', 'Great Admiral of Cecil'),
    ('LOC_GREAT_PERSON_INDIVIDUAL_TSOD_CE_BYRON_KIRK_NAME', 'Byron Kirk'),
    ('LOC_GREATPERSON_COMBAT_STRENGTH_AOE_ALL_ERA_SEA_DESCRIPTION', '+5 [ICON_Strength] Combat Strength to naval units within 2 tiles.'),
    ('LOC_GREATPERSON_GRANT_INFLUENCE_TOKEN_DESCRIPTION', 'Gain 1 [ICON_Envoy] envoy.'),
    ('LOC_GREAT_PERSON_CLASS_TSOD_CE_PROPHET_NAME', 'Great Patriarch of Cecil'),
    ('LOC_GREAT_PERSON_INDIVIDUAL_TSOD_CE_LEITE_AVIKEN_NAME', 'Leite Aviken'),
    ('LOC_ABILITY_COMBAT_STRENGTH_AOE_RELIGIOUS_NAME', 'Grand Sheperd''s guidance'),
    ('LOC_ABILITY_COMBAT_STRENGTH_AOE_RELIGIOUS_DESCRIPTION', '+5 [ICON_Religion] religious combat strength within 2 tiles adjacent to Grand Sheperd.'),
    ('LOC_COMBAT_STRENGTH_AOE_RELIGIOUS_DESCRIPTION', '+5 [ICON_Religion] religious combat strength within 2 tiles adjacent to Grand Sheperd.'),
    (
        'LOC_GREATPERSON_CITY_POPULATION_RELIGIOUS_YIELD_ATTACH_DESCRIPTION',
        'If this city follows any religion, +0.5 [ICON_Faith] faith yield per population.'
    ),
    ('LOC_GREAT_PERSON_CLASS_TSOD_CE_MERCHANT_NAME', 'Great Merchant of Cecil'),
    ('LOC_GREAT_PERSON_INDIVIDUAL_TSOD_CE_PITMAN_LAUREN_NAME', 'Pitman Lauren'),
    (
        'LOC_GREATPERSON_GRANT_LUXURY_POTION_DESCRIPTION',
        'Grants 2 [ICON_RESOURCE_TSOD_CE_POTION] Potion, a uniquely manufactured Luxury resource which provides +4 [ICON_Amenities] Amenities.'
    ),
    ('LOC_GREAT_PERSON_CLASS_TSOD_CE_WRITER_NAME', 'Great Playwright of Cecil'),
    ('LOC_GREAT_PERSON_INDIVIDUAL_TSOD_CE_FELM_NAME', 'Felm'),
    ('LOC_GREAT_PERSON_CLASS_TSOD_CE_ENGINEER_NAME', 'Great Engineer of Cecil'),
    ('LOC_GREAT_PERSON_INDIVIDUAL_TSOD_CE_NICHOLAS_EGG_NAME', 'Nicholas Egg'),
    (
        'LOC_GREATPERSON_AOE_TSOD_CE_NICHOLAS_EGG_ATTACH_DESCRIPTION',
        'When the unit is at or adjacent to city center, +25% [ICON_Production] towards unit production in this city.'
    ),
    ('LOC_UNIT_TSOD_GORGON_PLATFORM_NAME', 'Gorgon Platform'),
    (
        'LOC_UNIT_TSOD_GORGON_PLATFORM_DESCRIPTION',
        'Cecil''s Atomic era support unit, replaces drone. Adds +1 [ICON_Range] range and +5 [ICON_Strength] bombard strength to siege units within 1 hex. Can heal adjacent units.'
    ),
    (
        'LOC_TSOD_GORGON_PLATFORM_SIEGE_BONUS_DESCRIPTION',
        '+1 [ICON_Range] range and +5 [ICON_Strength] bombard strength to siege units adjacent to Gorgon Platform.'
    ),
    ('LOC_TSOD_GORGON_PLATFORM_SIEGE_BONUS_MODIFIER', '+{1_Amount} bombard strength adjacent to Gorgon Platform.'),
    ('LOC_PROMOTION_CLASS_TSOD_SCOUT_AMBER_NAME', 'Amber'),
    ('LOC_PROMOTION_TSOD_CE_SHADOW_REALM_NAME', 'Shadow Realm'),
    ('LOC_PROMOTION_TSOD_CE_SHADOW_REALM_DESCRIPTION', '+1 sight range. Can see through all terrain types and features.'),
    ('LOC_PROMOTION_TSOD_CE_MASTER_THIEF_NAME', 'Master Thief'),
    ('LOC_PROMOTION_TSOD_CE_MASTER_THIEF_DESCRIPTION', '+15 [ICON_Strength] combat strength against wounded enemies.'),
    ('LOC_PROMOTION_TSOD_CE_SHADOW_CREATURE_NAME', 'Shadow Creature'),
    ('LOC_PROMOTION_TSOD_CE_SHADOW_CREATURE_DESCRIPTION', '+1 [ICON_Movement] movement. Ignore movement penalties from all terrain types.'),
    ('LOC_PROMOTION_TSOD_CE_TAVERN_QUEEN_NAME', 'Tavern Queen'),
    (
        'LOC_PROMOTION_TSOD_CE_TAVERN_QUEEN_DESCRIPTION',
        'Heals outside of friendly territory. Will always heal at the end of turn regardless of action.'
    ),
    ('LOC_PROMOTION_TSOD_CE_SHADOW_CHOSEN_NAME', 'Night''s Chosen'),
    ('LOC_PROMOTION_TSOD_CE_SHADOW_CHOSEN_DESCRIPTION', '+1 [ICON_Movement] movement. Only adjacent enemy units can reveal this unit.'),
    ('LOC_PROMOTION_TSOD_CE_NIGHT_MISTRESS_NAME', 'Night Mistress'),
    ('LOC_PROMOTION_TSOD_CE_NIGHT_MISTRESS_DESCRIPTION', '+1 sight range, reveals invisible units within the vision range.'),
    ('LOC_PROMOTION_TSOD_CE_SHADOW_AUTHORITY_NAME', 'Shadow Authority'),
    ('LOC_PROMOTION_TSOD_CE_SHADOW_AUTHORITY_DESCRIPTION', 'Can move after attacking. +1 diplomatic rank with all civilizations.'),
    ('LOC_VIZSOURCE_TSOD_SCOUT_AMBER', 'Amber in Her Ultimate State!'),
    ('LOC_VIZSOURCE_ACTION_TSOD_SCOUT_AMBER', 'Promote Amber to the highest level.'),
    ('LOC_GOSSIP_SOURCE_TSOD_SCOUT_AMBER', '{1_Name}, uncovered news that');