INSERT
OR REPLACE INTO LocalizedText (Tag, LANGUAGE, Text)
VALUES
    ('LOC_RESOURCE_TSOD_CE_POTION_NAME', 'zh_Hans_CN', '炼金药剂');

INSERT
OR REPLACE INTO BaseGameText (Tag, Text)
VALUES
    ('LOC_RESOURCE_TSOD_CE_POTION_NAME', 'Potion');