INSERT INTO
    LocalizedText (Tag, Language, Text)
VALUES
    (
        'LOC_CIVILIZATION_TSOD_CECIL_EMPIRE_NAME',
        'zh_Hans_CN',
        '塞西尔帝国'
    ),
    (
        'LOC_CIVILIZATION_TSOD_CECIL_EMPIRE_DESCRIPTION',
        'zh_Hans_CN',
        '塞西尔帝国的介绍'
    ),
    (
        'LOC_CIVILIZATION_TSOD_CECIL_EMPIRE_ADJECTIVE',
        'zh_Hans_CN',
        '塞西尔帝国的'
    ),
    (
        'LOC_TRAIT_CIVILIZATION_TSOD_CECIL_EMPIRE_NAME',
        'zh_Hans_CN',
        '塞西尔帝国的技能'
    ),
    (
        'LOC_TRAIT_CIVILIZATION_TSOD_CECIL_EMPIRE_DESCRIPTION',
        'zh_Hans_CN',
        '塞西尔帝国的技能介绍'
    ),
    (
        'LOC_LEADER_TSOD_GAWAIN_CECIL_NAME',
        'zh_Hans_CN',
        '高文·塞西尔'
    ),
    (
        'LOC_TRAIT_LEADER_TSOD_GAWAIN_CECIL_NAME',
        'zh_Hans_CN',
        '高文·塞西尔的技能'
    ),
    (
        'LOC_TRAIT_LEADER_TSOD_GAWAIN_CECIL_DESCRIPTION',
        'zh_Hans_CN',
        '高文·塞西尔的技能介绍'
    ),
    (
        'LOC_LOADING_INFO_LEADER_TSOD_GAWAIN_CECIL',
        'zh_Hans_CN',
        '高文·塞西尔的生平介绍'
    ),
    (
        'LOC_LEADER_TSOD_GAWAIN_CECIL_GREETING',
        'zh_Hans_CN',
        '高文·塞西尔向你问好'
    ),
    ('LOC_CITY_NAME_TSOD_CECIL', 'zh_Hans_CN', '塞西尔城'),
    (
        'LOC_CITY_NAME_TSOD_SAINT_SUNIL',
        'zh_Hans_CN',
        '圣苏尼尔城'
    ),
    (
        'LOC_CITY_NAME_TSOD_LONGWIND_FORTRESS',
        'zh_Hans_CN',
        '长风要塞'
    ),
    (
        'LOC_CITY_NAME_TSOD_FROSTWOOD_VILLAGE',
        'zh_Hans_CN',
        '霜林村'
    ),
    (
        'LOC_CITY_NAME_TSOD_ROCKSTONE',
        'zh_Hans_CN',
        '磐石城'
    ),
    (
        'LOC_CITY_NAME_TSOD_MEGALITH',
        'zh_Hans_CN',
        '巨石城'
    ),
    ('LOC_CITY_NAME_TSOD_LUAN', 'zh_Hans_CN', '卢安城'),
    (
        'LOC_CITY_NAME_TSOD_RED_MAPLE',
        'zh_Hans_CN',
        '红枫城'
    ),
    ('LOC_CITY_NAME_TSOD_POMPEII', 'zh_Hans_CN', '庞贝城'),
    ('LOC_CITY_NAME_TSOD_ELRON', 'zh_Hans_CN', '埃尔隆城'),
    (
        'LOC_CITY_NAME_TSOD_FERTILE_WOODLANDS',
        'zh_Hans_CN',
        '丰饶林地'
    ),
    (
        'LOC_CITY_NAME_TSOD_SLANTWOOD_VALLEY',
        'zh_Hans_CN',
        '斜林河谷'
    ),
    (
        'LOC_CITY_NAME_TSOD_LONGSTONE_TOWN',
        'zh_Hans_CN',
        '长石镇'
    ),
    (
        'LOC_CITY_NAME_TSOD_TENWOODS',
        'zh_Hans_CN',
        '十林城'
    ),
    (
        'LOC_CITY_NAME_TSOD_TAMDULUR',
        'zh_Hans_CN',
        '塔姆杜勒'
    ),
    (
        'LOC_CITY_NAME_TSOD_LUNTATELLE_SHIRE',
        'zh_Hans_CN',
        '伦塔特尔郡'
    ),
    (
        'LOC_CITY_NAME_TSOD_HOLLE_SHIRE',
        'zh_Hans_CN',
        '霍尔郡'
    ),
    ('LOC_CITIZEN_NAME_TSOD_SAM', 'zh_Hans_CN', '山姆'),
    ('LOC_CITIZEN_NAME_TSOD_TOM', 'zh_Hans_CN', '汤姆'),
    ('LOC_CITIZEN_NAME_TSOD_PEA', 'zh_Hans_CN', '豌豆'),
    (
        'LOC_CITIZEN_NAME_TSOD_JENNIE_PERRO',
        'zh_Hans_CN',
        '詹妮·佩罗'
    ),
    (
        'LOC_CITIZEN_NAME_TSOD_GORDON',
        'zh_Hans_CN',
        '戈登'
    ),
    ('LOC_CITIZEN_NAME_TSOD_HALL', 'zh_Hans_CN', '霍尔'),
    (
        'LOC_CITIZEN_NAME_TSOD_ELVIN_FRANKLIN',
        'zh_Hans_CN',
        '伊莱文·法兰克林'
    ),
    (
        'LOC_CITIZEN_NAME_TSOD_FENDIL_WILDER',
        'zh_Hans_CN',
        '芬迪尔·维尔德'
    ),
    (
        'LOC_CITIZEN_NAME_TSOD_VICTORIA_WILDER',
        'zh_Hans_CN',
        '维多利亚·维尔德'
    ),
    (
        'LOC_CITIZEN_NAME_TSOD_CROMWELL_WHITEMOUNTAIN',
        'zh_Hans_CN',
        '克伦威尔·白山'
    ),
    (
        'LOC_CITIZEN_NAME_TSOD_BODWIN_FRANKLIN',
        'zh_Hans_CN',
        '柏德文·法兰克林'
    ),
    (
        'LOC_CITIZEN_NAME_TSOD_VERONICA_MOEN',
        'zh_Hans_CN',
        '维罗妮卡·摩恩'
    ),
    (
        'LOC_CITIZEN_NAME_TSOD_SEWEN_TERRY',
        'zh_Hans_CN',
        '赛文·特里'
    ),
    (
        'LOC_CITIZEN_NAME_TSOD_HAMEL',
        'zh_Hans_CN',
        '汉默尔'
    ),
    ('LOC_CITIZEN_NAME_TSOD_HOLM', 'zh_Hans_CN', '霍姆'),
    (
        'LOC_CITIZEN_NAME_TSOD_MARGARITA',
        'zh_Hans_CN',
        '玛格丽塔'
    ),
    ('LOC_CITIZEN_NAME_TSOD_BETTY', 'zh_Hans_CN', '贝蒂'),
    (
        'LOC_CITIZEN_NAME_TSOD_WITCH_GIPLY',
        'zh_Hans_CN',
        ''' 女巫 ''吉普莉'
    ),
    (
        'LOC_CITIZEN_NAME_TSOD_SCARFACE_ANTON',
        'zh_Hans_CN',
        ''' 疤脸 ''安东'
    );