INSERT INTO
    Types (Type, Kind)
VALUES
    ('GREATWORK_TSOD_CE_IMMIGRANTS', 'KIND_GREATWORK'),
    ('GREATWORK_TSOD_CE_BEACON_FIRE', 'KIND_GREATWORK');

INSERT INTO
    Greatworks (GreatWorkType, GreatWorkObjectType, GreatPersonIndividualType, Name, Quote, Tourism)
VALUES
    (
        'GREATWORK_TSOD_CE_IMMIGRANTS',
        'GREATWORKOBJECT_WRITING',
        'GREAT_PERSON_INDIVIDUAL_TSOD_CE_FELM',
        'LOC_GREATWORK_TSOD_CE_IMMIGRANTS_NAME',
        'LOC_GREATWORK_TSOD_CE_IMMIGRANTS_QUOTE',
        4
    ),
    (
        'GREATWORK_TSOD_CE_BEACON_FIRE',
        'GREATWORKOBJECT_WRITING',
        'GREAT_PERSON_INDIVIDUAL_TSOD_CE_FELM',
        'LOC_GREATWORK_TSOD_CE_BEACON_FIRE_NAME',
        'LOC_GREATWORK_TSOD_CE_BEACON_FIRE_QUOTE',
        4
    );

INSERT INTO
    GreatWork_YieldChanges (GreatWorkType, YieldType, YieldChange)
VALUES
    ('GREATWORK_TSOD_CE_IMMIGRANTS', 'YIELD_CULTURE', 6),
    ('GREATWORK_TSOD_CE_BEACON_FIRE', 'YIELD_CULTURE', 6);