INSERT INTO
    Types (Type, Kind)
VALUES
    ('LEADER_TSOD_GAWAIN_CECIL', 'KIND_LEADER'),
    ('TRAIT_LEADER_TSOD_GAWAIN_CECIL', 'KIND_TRAIT');

INSERT INTO
    Leaders (LeaderType, Name, InheritFrom, Sex)
VALUES
    ('LEADER_TSOD_GAWAIN_CECIL', 'LOC_LEADER_TSOD_GAWAIN_CECIL_NAME', 'LEADER_DEFAULT', 'Male');

INSERT INTO
    LeaderQuotes (LeaderType, Quote)
VALUES
    ('LEADER_TSOD_GAWAIN_CECIL', 'LOC_LEADER_TSOD_GAWAIN_CECIL_GREETING');

-- INSERT INTO
--     HistoricalAgendas (LeaderType, AgendaType)
-- VALUES
--     ('LEADER_TSOD_GAWAIN_CECIL', 'AGENDA_TSOD_CE_KNIGHTS_OVER_MAGES');

INSERT INTO
    LeaderTraits (LeaderType, TraitType)
VALUES
    ('LEADER_TSOD_GAWAIN_CECIL', 'TRAIT_LEADER_TSOD_GAWAIN_CECIL'),
    ('LEADER_TSOD_GAWAIN_CECIL', 'TRAIT_LEADER_SCIENCE_MAJOR_CIV'),
    ('LEADER_TSOD_GAWAIN_CECIL', 'TRAIT_LEADER_NONRELIGIOUS_MAJOR_CIV'),
    ('LEADER_TSOD_GAWAIN_CECIL', 'TRAIT_LEADER_LOW_CITY_STATE_PREFERENCE_WAR'),
    ('LEADER_TSOD_GAWAIN_CECIL', 'TRAIT_LEADER_AGGRESSIVE_MILITARY');

INSERT INTO
    Traits (TraitType, Name, Description)
VALUES
    ('TRAIT_LEADER_TSOD_GAWAIN_CECIL', 'LOC_TRAIT_LEADER_TSOD_GAWAIN_CECIL_NAME', 'LOC_TRAIT_LEADER_TSOD_GAWAIN_CECIL_DESCRIPTION');

INSERT INTO
    LoadingInfo (LeaderType, ForegroundImage, BackgroundImage, PlayDawnOfManAudio, LeaderText)
VALUES
    (
        'LEADER_TSOD_GAWAIN_CECIL',
        'LEADER_TSOD_GAWAIN_CECIL_LOADING_FOREGROUND',
        'LEADER_TSOD_GAWAIN_CECIL_LOADING_BACKGROUND',
        '1',
        'LOC_LOADING_INFO_LEADER_TSOD_GAWAIN_CECIL'
    );

INSERT INTO
    DiplomacyInfo (Type, BackgroundImage)
VALUES
    ('LEADER_TSOD_GAWAIN_CECIL', 'LEADER_TSOD_GAWAIN_CECIL_DIPLOMACY_BACKGROUND');