INSERT INTO
    Types (Type, Kind)
VALUES
    ('PROMOTION_CLASS_TSOD_SCOUT_AMBER', 'KIND_PROMOTION_CLASS'),
    ('PROMOTION_TSOD_CE_SHADOW_REALM', 'KIND_PROMOTION'),
    ('PROMOTION_TSOD_CE_MASTER_THIEF', 'KIND_PROMOTION'),
    ('PROMOTION_TSOD_CE_SHADOW_CREATURE', 'KIND_PROMOTION'),
    ('PROMOTION_TSOD_CE_TAVERN_QUEEN', 'KIND_PROMOTION'),
    ('PROMOTION_TSOD_CE_SHADOW_CHOSEN', 'KIND_PROMOTION'),
    ('PROMOTION_TSOD_CE_NIGHT_MISTRESS', 'KIND_PROMOTION'),
    ('PROMOTION_TSOD_CE_SHADOW_AUTHORITY', 'KIND_PROMOTION');

INSERT INTO
    UnitPromotionClasses (PromotionClassType, Name)
VALUES
    ('PROMOTION_CLASS_TSOD_SCOUT_AMBER', 'LOC_PROMOTION_CLASS_TSOD_SCOUT_AMBER_NAME');

INSERT INTO
    UnitPromotions (UnitPromotionType, Name, Description, Level, COLUMN, PromotionClass)
VALUES
    (
        'PROMOTION_TSOD_CE_SHADOW_REALM',
        'LOC_PROMOTION_TSOD_CE_SHADOW_REALM_NAME',
        'LOC_PROMOTION_TSOD_CE_SHADOW_REALM_DESCRIPTION',
        1,
        1,
        'PROMOTION_CLASS_TSOD_SCOUT_AMBER'
    ),
    (
        'PROMOTION_TSOD_CE_MASTER_THIEF',
        'LOC_PROMOTION_TSOD_CE_MASTER_THIEF_NAME',
        'LOC_PROMOTION_TSOD_CE_MASTER_THIEF_DESCRIPTION',
        1,
        3,
        'PROMOTION_CLASS_TSOD_SCOUT_AMBER'
    ),
    (
        'PROMOTION_TSOD_CE_SHADOW_CREATURE',
        'LOC_PROMOTION_TSOD_CE_SHADOW_CREATURE_NAME',
        'LOC_PROMOTION_TSOD_CE_SHADOW_CREATURE_DESCRIPTION',
        2,
        1,
        'PROMOTION_CLASS_TSOD_SCOUT_AMBER'
    ),
    (
        'PROMOTION_TSOD_CE_TAVERN_QUEEN',
        'LOC_PROMOTION_TSOD_CE_TAVERN_QUEEN_NAME',
        'LOC_PROMOTION_TSOD_CE_TAVERN_QUEEN_DESCRIPTION',
        2,
        3,
        'PROMOTION_CLASS_TSOD_SCOUT_AMBER'
    ),
    (
        'PROMOTION_TSOD_CE_SHADOW_CHOSEN',
        'LOC_PROMOTION_TSOD_CE_SHADOW_CHOSEN_NAME',
        'LOC_PROMOTION_TSOD_CE_SHADOW_CHOSEN_DESCRIPTION',
        3,
        1,
        'PROMOTION_CLASS_TSOD_SCOUT_AMBER'
    ),
    (
        'PROMOTION_TSOD_CE_NIGHT_MISTRESS',
        'LOC_PROMOTION_TSOD_CE_NIGHT_MISTRESS_NAME',
        'LOC_PROMOTION_TSOD_CE_NIGHT_MISTRESS_DESCRIPTION',
        3,
        3,
        'PROMOTION_CLASS_TSOD_SCOUT_AMBER'
    ),
    (
        'PROMOTION_TSOD_CE_SHADOW_AUTHORITY',
        'LOC_PROMOTION_TSOD_CE_SHADOW_AUTHORITY_NAME',
        'LOC_PROMOTION_TSOD_CE_SHADOW_AUTHORITY_DESCRIPTION',
        4,
        2,
        'PROMOTION_CLASS_TSOD_SCOUT_AMBER'
    );

INSERT INTO
    UnitPromotionPrereqs (UnitPromotion, PrereqUnitPromotion)
VALUES
    ('PROMOTION_TSOD_CE_SHADOW_CREATURE', 'PROMOTION_TSOD_CE_SHADOW_REALM'),
    ('PROMOTION_TSOD_CE_TAVERN_QUEEN', 'PROMOTION_TSOD_CE_SHADOW_CREATURE'),
    ('PROMOTION_TSOD_CE_TAVERN_QUEEN', 'PROMOTION_TSOD_CE_MASTER_THIEF'),
    ('PROMOTION_TSOD_CE_SHADOW_CHOSEN', 'PROMOTION_TSOD_CE_SHADOW_CREATURE'),
    ('PROMOTION_TSOD_CE_NIGHT_MISTRESS', 'PROMOTION_TSOD_CE_SHADOW_CHOSEN'),
    ('PROMOTION_TSOD_CE_NIGHT_MISTRESS', 'PROMOTION_TSOD_CE_TAVERN_QUEEN'),
    ('PROMOTION_TSOD_CE_SHADOW_AUTHORITY', 'PROMOTION_TSOD_CE_SHADOW_CHOSEN');

INSERT INTO
    UnitPromotionModifiers (UnitPromotionType, ModifierId)
VALUES
    ('PROMOTION_TSOD_CE_SHADOW_REALM', 'SPYGLASS_BONUS_SIGHT'),
    ('PROMOTION_TSOD_CE_SHADOW_REALM', 'UNOBSTRUCTED_VIEW'),
    ('PROMOTION_TSOD_CE_SHADOW_REALM', 'UNOBSTRUCTED_VIEW_TERRAIN'),
    ('PROMOTION_TSOD_CE_MASTER_THIEF', 'MODIFIER_TSOD_CE_MASTER_THIEF_BONUS_VS_WOUNDED_UNITS'),
    ('PROMOTION_TSOD_CE_SHADOW_CREATURE', 'MOD_IGNORE_TERRAIN_COST'),
    ('PROMOTION_TSOD_CE_SHADOW_CREATURE', 'MOD_IGNORE_CROSSING_RIVERS_COST'),
    ('PROMOTION_TSOD_CE_SHADOW_CREATURE', 'MODIFIER_TSOD_CE_SHADOW_CREATURE_MOVEMENT'),
    ('PROMOTION_TSOD_CE_TAVERN_QUEEN', 'MAMLUK_HEAL_EVERY_MOVE'),
    ('PROMOTION_TSOD_CE_TAVERN_QUEEN', 'SUPPLY_FLEET_NEUTRAL_TERRITORY_HEAL'),
    ('PROMOTION_TSOD_CE_TAVERN_QUEEN', 'SUPPLY_FLEET_ENEMY_TERRITORY_HEAL'),
    ('PROMOTION_TSOD_CE_SHADOW_CHOSEN', 'MODIFIER_TSOD_CE_SHADOW_CHOSEN_MOVEMENT'),
    ('PROMOTION_TSOD_CE_SHADOW_CHOSEN', 'CAMOUFLAGE_STEALTH'),
    ('PROMOTION_TSOD_CE_NIGHT_MISTRESS', 'MODIFIER_TSOD_CE_NIGHT_MISTRESS_BONUS_SIGHT'),
    ('PROMOTION_TSOD_CE_NIGHT_MISTRESS', 'UNIT_SEE_HIDDEN'),
    ('PROMOTION_TSOD_CE_SHADOW_AUTHORITY', 'MOD_MOVE_AFTER_ATTACKING'),
    ('PROMOTION_TSOD_CE_SHADOW_AUTHORITY', 'MODIFIER_TSOD_CE_SHADOW_AUTHORITY_ATTACH_DIPLO_MOD');

INSERT INTO
    Modifiers (ModifierId, ModifierType, SubjectRequirementSetId)
VALUES
    ('MODIFIER_TSOD_CE_SHADOW_CREATURE_MOVEMENT', 'MODIFIER_PLAYER_UNIT_ADJUST_MOVEMENT', NULL),
    ('MODIFIER_TSOD_CE_MASTER_THIEF_BONUS_VS_WOUNDED_UNITS', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', 'REQUIREMENTS_OPPONENT_IS_WOUNDED'),
    ('MODIFIER_TSOD_CE_SHADOW_CHOSEN_MOVEMENT', 'MODIFIER_PLAYER_UNIT_ADJUST_MOVEMENT', NULL),
    ('MODIFIER_TSOD_CE_NIGHT_MISTRESS_BONUS_SIGHT', 'MODIFIER_PLAYER_UNIT_ADJUST_SIGHT', NULL),
    ('MODIFIER_TSOD_CE_SHADOW_AUTHORITY_ATTACH_DIPLO_MOD', 'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER', 'PLAYER_IS_TSOD_CECIL_EMPIRE_REQUIREMENTS'),
    ('MODIFIER_TSOD_CE_SHADOW_AUTHORITY_BONUS_DIPLO_VISIBILITY', 'MODIFIER_PLAYER_ADD_DIPLO_VISIBILITY', NULL);

INSERT INTO
    ModifierArguments (ModifierId, Name, VALUE)
VALUES
    ('MODIFIER_TSOD_CE_SHADOW_CREATURE_MOVEMENT', 'Amount', '1'),
    ('MODIFIER_TSOD_CE_MASTER_THIEF_BONUS_VS_WOUNDED_UNITS', 'Amount', '15'),
    ('MODIFIER_TSOD_CE_SHADOW_CHOSEN_MOVEMENT', 'Amount', '1'),
    ('MODIFIER_TSOD_CE_NIGHT_MISTRESS_BONUS_SIGHT', 'Amount', '1'),
    ('MODIFIER_TSOD_CE_SHADOW_AUTHORITY_ATTACH_DIPLO_MOD', 'ModifierId', 'MODIFIER_TSOD_CE_SHADOW_AUTHORITY_BONUS_DIPLO_VISIBILITY'),
    ('MODIFIER_TSOD_CE_SHADOW_AUTHORITY_BONUS_DIPLO_VISIBILITY', 'Amount', '1'),
    ('MODIFIER_TSOD_CE_SHADOW_AUTHORITY_BONUS_DIPLO_VISIBILITY', 'Source', 'SOURCE_TSOD_SCOUT_AMBER'),
    ('MODIFIER_TSOD_CE_SHADOW_AUTHORITY_BONUS_DIPLO_VISIBILITY', 'SourceType', 'DIPLO_SOURCE_ALL_NAMES');

INSERT INTO
    ModifierStrings (ModifierId, Context, Text)
VALUES
    ('MODIFIER_TSOD_CE_MASTER_THIEF_BONUS_VS_WOUNDED_UNITS', 'Preview', 'LOC_PROMOTION_TSOD_CE_MASTER_THIEF_DESCRIPTION');

INSERT INTO
    DiplomaticVisibilitySources (VisibilitySourceType, Description, ActionDescription, GossipString, FromCitizen, TraitType)
VALUES
    (
        'SOURCE_TSOD_SCOUT_AMBER',
        'LOC_VIZSOURCE_TSOD_SCOUT_AMBER',
        'LOC_VIZSOURCE_ACTION_TSOD_SCOUT_AMBER',
        'LOC_GOSSIP_SOURCE_TSOD_SCOUT_AMBER',
        1,
        'TRAIT_UNIT_TSOD_SCOUT_AMBER'
    )