INSERT INTO
    MajorStartingUnits (Era, Unit, OnDistrictCreated, NotStartTile)
VALUES
    (
        'ERA_ANCIENT',
        'UNIT_TSOD_SCOUT_AMBER',
        1,
        1
    ),
    (
        'ERA_CLASSICAL',
        'UNIT_TSOD_SCOUT_AMBER',
        1,
        1
    ),
    (
        'ERA_MEDIEVAL',
        'UNIT_TSOD_SCOUT_AMBER',
        1,
        1
    ),
    (
        'ERA_RENAISSANCE',
        'UNIT_TSOD_SCOUT_AMBER',
        1,
        1
    ),
    (
        'ERA_INDUSTRIAL',
        'UNIT_TSOD_SCOUT_AMBER',
        1,
        1
    ),
    (
        'ERA_MODERN',
        'UNIT_TSOD_SCOUT_AMBER',
        1,
        1
    ),
    (
        'ERA_ATOMIC',
        'UNIT_TSOD_SCOUT_AMBER',
        1,
        1
    ),
    (
        'ERA_INFORMATION',
        'UNIT_TSOD_SCOUT_AMBER',
        1,
        1
    );